// Mocks generated by Mockito 5.0.16 from annotations
// in tv/test/tv_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:convert' as _i20;
import 'dart:typed_data' as _i21;

import 'package:core/database/database_helper.dart' as _i6;
import 'package:core/utils/failure.dart' as _i13;
import 'package:core/utils/network_info.dart' as _i11;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie/data/models/movie_table.dart' as _i10;
import 'package:sqflite/sqflite.dart' as _i8;
import 'package:tv/data/datasources/tv_local_data_source.dart' as _i17;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i18;
import 'package:tv/data/models/season_detail_model.dart' as _i4;
import 'package:tv/data/models/tv_detail_model.dart' as _i3;
import 'package:tv/data/models/tv_model.dart' as _i19;
import 'package:tv/data/models/tv_table.dart' as _i9;
import 'package:tv/domain/entities/season_detail.dart' as _i16;
import 'package:tv/domain/entities/tv.dart' as _i14;
import 'package:tv/domain/entities/tv_detail.dart' as _i15;
import 'package:tv/domain/repositories/tv_repository.dart' as _i12;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

class _FakeTvDetailModel_1 extends _i1.Fake implements _i3.TvDetailModel {}

class _FakeSeasonDetailModel_2 extends _i1.Fake
    implements _i4.SeasonDetailModel {}

class _FakeResponse_3 extends _i1.Fake implements _i5.Response {}

class _FakeStreamedResponse_4 extends _i1.Fake implements _i5.StreamedResponse {
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i6.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.Database?> get database => (super.noSuchMethod(
      Invocation.getter(#database),
      returnValue: Future<_i8.Database?>.value()) as _i7.Future<_i8.Database?>);
  @override
  _i7.Future<void> insertTvCacheTransaction(
          List<_i9.TvTable>? tvs, String? category) =>
      (super.noSuchMethod(
          Invocation.method(#insertTvCacheTransaction, [tvs, category]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<void> insertCacheTransaction(
          List<_i10.MovieTable>? movies, String? category) =>
      (super.noSuchMethod(
          Invocation.method(#insertCacheTransaction, [movies, category]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheTvs(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheTvs, [category]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getCacheMovies(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheMovies, [category]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  _i7.Future<int> clearTvCache(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearTvCache, [category]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> clearCache(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearCache, [category]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> insertWatchlist(_i10.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> insertTvWatchList(_i9.TvTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertTvWatchList, [tv]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> removeTvWatchlist(_i9.TvTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [tv]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> removeWatchlist(_i10.MovieTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistMovies, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistTvs() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvs, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i11.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i12.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i13.Failure, List<_i14.Tv>>> getNowPlayingTvs() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvs, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Tv>>())) as _i7
          .Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, List<_i14.Tv>>> getPopularTvs() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvs, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Tv>>())) as _i7
          .Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, List<_i14.Tv>>> getTopRatedTvs() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvs, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Tv>>())) as _i7
          .Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, _i15.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
          returnValue: Future<_i2.Either<_i13.Failure, _i15.TvDetail>>.value(
              _FakeEither_0<_i13.Failure, _i15.TvDetail>())) as _i7
          .Future<_i2.Either<_i13.Failure, _i15.TvDetail>>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, List<_i14.Tv>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Tv>>())) as _i7
          .Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, List<_i14.Tv>>> searchTvs(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvs, [query]),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Tv>>())) as _i7
          .Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, String>> saveWatchlist(
          _i15.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tv]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i7.Future<_i2.Either<_i13.Failure, String>>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, String>> removeWatchlist(
          _i15.TvDetail? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tv]),
              returnValue: Future<_i2.Either<_i13.Failure, String>>.value(
                  _FakeEither_0<_i13.Failure, String>()))
          as _i7.Future<_i2.Either<_i13.Failure, String>>);
  @override
  _i7.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, List<_i14.Tv>>> getWatchlistTvs() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvs, []),
          returnValue: Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>.value(
              _FakeEither_0<_i13.Failure, List<_i14.Tv>>())) as _i7
          .Future<_i2.Either<_i13.Failure, List<_i14.Tv>>>);
  @override
  _i7.Future<_i2.Either<_i13.Failure, _i16.SeasonDetail>> getSeasonDetail(
          int? id, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getSeasonDetail, [id, seasonNumber]),
              returnValue:
                  Future<_i2.Either<_i13.Failure, _i16.SeasonDetail>>.value(
                      _FakeEither_0<_i13.Failure, _i16.SeasonDetail>()))
          as _i7.Future<_i2.Either<_i13.Failure, _i16.SeasonDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i17.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertWatchlist(_i9.TvTable? tv) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [tv]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<String> removeWatchlist(_i9.TvTable? tv) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tv]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i9.TvTable?> getTvById(int? id) => (super.noSuchMethod(
      Invocation.method(#getTvById, [id]),
      returnValue: Future<_i9.TvTable?>.value()) as _i7.Future<_i9.TvTable?>);
  @override
  _i7.Future<List<_i9.TvTable>> getWatchlistTvs() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvs, []),
              returnValue: Future<List<_i9.TvTable>>.value(<_i9.TvTable>[]))
          as _i7.Future<List<_i9.TvTable>>);
  @override
  _i7.Future<void> cacheNowPlayingTvs(List<_i9.TvTable>? tvs) =>
      (super.noSuchMethod(Invocation.method(#cacheNowPlayingTvs, [tvs]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i7.Future<void>);
  @override
  _i7.Future<List<_i9.TvTable>> getCachedNowPlayingTvs() =>
      (super.noSuchMethod(Invocation.method(#getCachedNowPlayingTvs, []),
              returnValue: Future<List<_i9.TvTable>>.value(<_i9.TvTable>[]))
          as _i7.Future<List<_i9.TvTable>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i18.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i19.TvModel>> getNowPlayingTvs() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvs, []),
              returnValue: Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]))
          as _i7.Future<List<_i19.TvModel>>);
  @override
  _i7.Future<List<_i19.TvModel>> getTopRatedTvs() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvs, []),
              returnValue: Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]))
          as _i7.Future<List<_i19.TvModel>>);
  @override
  _i7.Future<List<_i19.TvModel>> getPopularTvs() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvs, []),
              returnValue: Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]))
          as _i7.Future<List<_i19.TvModel>>);
  @override
  _i7.Future<_i3.TvDetailModel> getTvDetail(int? id) => (super.noSuchMethod(
          Invocation.method(#getTvDetail, [id]),
          returnValue: Future<_i3.TvDetailModel>.value(_FakeTvDetailModel_1()))
      as _i7.Future<_i3.TvDetailModel>);
  @override
  _i7.Future<_i4.SeasonDetailModel> getSeasonDetail(
          int? id, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getSeasonDetail, [id, seasonNumber]),
              returnValue: Future<_i4.SeasonDetailModel>.value(
                  _FakeSeasonDetailModel_2()))
          as _i7.Future<_i4.SeasonDetailModel>);
  @override
  _i7.Future<List<_i19.TvModel>> searchTvs(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvs, [query]),
              returnValue: Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]))
          as _i7.Future<List<_i19.TvModel>>);
  @override
  _i7.Future<List<_i19.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue: Future<List<_i19.TvModel>>.value(<_i19.TvModel>[]))
          as _i7.Future<List<_i19.TvModel>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i20.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i20.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i20.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i20.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i21.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i21.Uint8List>.value(_i21.Uint8List(0)))
          as _i7.Future<_i21.Uint8List>);
  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4()))
          as _i7.Future<_i5.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
